language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-[0-9a-f]{8}
    - '.*intel.+'
script: ./gradlew assemble